// # Reasoning: Explicit type references ensure the TypeScript compiler understands modern WebGPU APIs.
/// <reference types="@webgpu/types" />

// # Reasoning: Importing the ES6 module generated by Emscripten allows seamless WASM instantiation.
import Module from '../public/compute.js';
//import Module from '/compute.js';

async function initArchitecture() {
    const statusElement = document.getElementById('status-overlay');
    if (!statusElement) return;

    // --- Phase 1: WASM Initialisation ---
    const wasmModule = await Module();
    
    // # Reasoning: The 'ccall' method safely bridges JavaScript types with C++ types.
    const multiplierResult = wasmModule.ccall('calculate_multiplier', 'number', ['number'], [10.0]);
    statusElement.innerText = `WASM Output (10.0 * 2.5) = ${multiplierResult}\nInitialising WebGPU...`;

    // --- Phase 2: WebGPU Initialisation ---
    if (!navigator.gpu) {
        statusElement.innerText += '\nError: WebGPU is not supported in this environment.';
        return;
    }

    const adapter = await navigator.gpu.requestAdapter();
    if (!adapter) {
        statusElement.innerText += '\nError: Failed to find a compatible WebGPU adapter.';
        return;
    }

    const device = await adapter.requestDevice();
    const canvas = document.getElementById('webgpu-canvas') as HTMLCanvasElement;
    const context = canvas.getContext('webgpu');
    
    if (!context) return;

    const presentationFormat = navigator.gpu.getPreferredCanvasFormat();
    context.configure({
        device,
        format: presentationFormat,
        alphaMode: 'premultiplied',
    });

    // # Reasoning: A simple render pass clearing to a specific colour confirms the GPU pipeline is functioning.
    const commandEncoder = device.createCommandEncoder();
    const textureView = context.getCurrentTexture().createView();

    const renderPassDescriptor: GPURenderPassDescriptor = {
        colorAttachments: [{
            view: textureView,
            // clearValue: { r: 0.15, g: 0.25, b: 0.35, a: 1.0 }, // blue
            clearValue: { r: 0.0, g: 0.00, b: 0.00, a: 1.0 }, // black
            loadOp: 'clear',
            storeOp: 'store',
        }],
    };

    const passEncoder = commandEncoder.beginRenderPass(renderPassDescriptor);
    passEncoder.end();

    device.queue.submit([commandEncoder.finish()]);
    
    statusElement.innerText += '\nSuccess: WebGPU pipeline active and rendering.';
}

initArchitecture();